version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - streamlit-app
      - fastapi-server

  streamlit-app:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./uploaded_pdfs:/app/uploaded_pdfs
      - ./log_folder:/app/log_folder

  fastapi-server:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded_pdfs:/app/uploaded_pdfs
      - ./log_folder:/app/log_folder
    env_file:
      - ./.env
